FROM public.ecr.aws/lambda/python:3.13.2025.07.06.12

COPY requirements.txt .
RUN pip3 install -r requirements.txt --target "${LAMBDA_TASK_ROOT}"

COPY src/common.py ${LAMBDA_TASK_ROOT}
COPY src/pocket.py ${LAMBDA_TASK_ROOT}

CMD [ "pocket.lambda_handler" ]
